### ISSUE TITLE
Database connection using password

### ISSUE THREAD

**Issue by Krakenied** [ThalKod/discord-clone#196]
How to connect mongodb using username, password, host and database name?

**Comment by ThalKod** [comment]
The Standard URI Scheme is 
`mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]` 
By example you can use: `mongodb://username:password@abc.com/`

**Comment by Krakenied** [comment]
What should I do if my database is on another server?
`Error: listen EPERM 0.0.0.0:5000
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1258:19)
    at listen (net.js:1307:10)
    at Server.listen (net.js:1403:5)
    at mongoose.connect.then (/xxx/public_nodejs/app.js:38:16)
    at process._tickCallback (internal/process/next_tick.js:109:7)`
